parrasdev/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    todo_list_ids, todo_list_ids_titles, todo_list_unresolved,
    todo_list_resolved, todo_list_ids_userids, todo_list_resolved_userids,
    todo_list_unresolved_userids,register, login_view,home,create_task, delete_task, update_task,logout_view
)

urlpatterns = [
    path('todos/ids/', todo_list_ids, name='todo-list-ids'),
    path('todos/ids-titles/', todo_list_ids_titles, name='todo-list-ids-titles'),
    path('todos/unresolved/', todo_list_unresolved, name='todo-list-unresolved'),
    path('todos/resolved/', todo_list_resolved, name='todo-list-resolved'),
    path('todos/ids-userids/', todo_list_ids_userids, name='todo-list-ids-userids'),
    path('todos/resolved-userids/', todo_list_resolved_userids, name='todo-list-resolved-userids'),
    path('todos/unresolved-userids/', todo_list_unresolved_userids, name='todo-list-unresolved-userids'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('', home, name='home'),
    path('create/', create_task, name='create_task'),
    path('delete/<int:task_id>/', delete_task, name='delete_task'),
    path('update/<int:task_id>/', update_task, name='update_task'),
]

todos/models.py
from django.db import models
from django.contrib.auth.models import User

class ToDo(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_resolved = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todos/forms.py
from django import forms
from .models import ToDo
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['title', 'description', 'user', 'is_resolved']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'user': forms.Select(attrs={'class': 'form-control'}),
            'is_resolved': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

todos/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import ToDo
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from .forms import ToDoForm
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.models import User

# Create your views here.

def todo_list_ids(request):
    todos = ToDo.objects.values_list('id', flat=True)
    return render(request, 'todos/todo_list_ids.html', {'todos': todos})

def todo_list_ids_titles(request):
    todos = ToDo.objects.values('id', 'title')
    return render(request, 'todos/todo_list_ids_titles.html', {'todos': todos})

def todo_list_unresolved(request):
    todos = ToDo.objects.filter(is_resolved=False).values('id', 'title')
    return render(request, 'todos/todo_list_unresolved.html', {'todos': todos})

def todo_list_resolved(request):
    todos = ToDo.objects.filter(is_resolved=True).values('id', 'title')
    return render(request, 'todos/todo_list_resolved.html', {'todos': todos})

def todo_list_ids_userids(request):
    todos = ToDo.objects.values('id', 'user_id')
    return render(request, 'todos/todo_list_ids_userids.html', {'todos': todos})

def todo_list_resolved_userids(request):
    todos = ToDo.objects.filter(is_resolved=True).values('id', 'user_id')
    return render(request, 'todos/todo_list_resolved_userids.html', {'todos': todos})

def todo_list_unresolved_userids(request):
    todos = ToDo.objects.filter(is_resolved=False).values('id', 'user_id')
    return render(request, 'todos/todo_list_unresolved_userids.html', {'todos': todos})


def home(request):
    unresolved_tasks = list(ToDo.objects.filter(is_resolved=False).values('id', 'title'))
    resolved_tasks = list(ToDo.objects.filter(is_resolved=True).values('title'))

    context = {
        'unresolved_tasks': unresolved_tasks,
        'resolved_tasks': resolved_tasks,
    }
    return render(request, 'todos/home.html', context)

def create_task(request):
    if request.method == 'POST':
        form = ToDoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')  
        else:
            messages.error(request, 'Error al crear la tarea')
    else:
        form = ToDoForm()

    context = {
        'form': form
    }
    return render(request, 'todos/create_task.html', context)

def delete_task(request, task_id):
    task = get_object_or_404(ToDo, pk=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('home')

    return render(request, 'todos/delete_task.html', {'task': task})

def update_task(request, task_id):
    task = get_object_or_404(ToDo, id=task_id)
    users = User.objects.all()
    if request.method == 'POST':
        form = ToDoForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ToDoForm(instance=task)

    context = {
        'form': form,
        'task': task,
        'users': users,
    }
    return render(request, 'todos/update_task.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'La cuenta de {username} ha sido creada. Ahora puedes iniciar sesión')
            return redirect('login')  
    else:
        form = UserRegisterForm()
    return render(request, 'todos/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f'Has iniciado sesión como {username}')
                return redirect('home')  
            else:
                messages.error(request, 'Usuario o contraseña incorrectos')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos')
    else:
        form = AuthenticationForm()
    return render(request, 'todos/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login')

todos/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Tareas App{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Menú de Tareas</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-list-ids' %}">Lista de IDs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-list-ids-titles' %}">Lista de IDs y Títulos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-list-unresolved' %}">Tareas No Resueltas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-list-resolved' %}">Tareas Resueltas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-list-ids-userids' %}">IDs y User IDs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-list-resolved-userids' %}">Tareas Resueltas con User IDs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-list-unresolved-userids' %}">Tareas No Resueltas con User IDs</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Registrarse</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-5">
        {% block content %}

        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js" integrity="sha384-NRQ2vP5QN7WuKiY1AqpOT9GhHvRlxD5WuAuAETOHSKAU4A8lW5a0ccVi3XvrzZJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+ozL0rADDDz2rC4fFVjlBpq5nl+YBjZA1Mz" crossorigin="anonymous"></script>
</body>
</html>

todos/templates/todos/create_task.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Tarea</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>
    <!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Tarea</title>
</head>
<body>
    <div class="container mt-5">
        <h2>Crear Tarea</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Título:</label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_description">Descripción:</label>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="id_user">Usuario:</label>
                {{ form.user }}
            </div>
            <div class="form-check">
                {{ form.is_resolved }}
                <label class="form-check-label" for="id_is_resolved">¿Resuelta?</label>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Crear Tarea</button>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-gH7kH+GD4wEXsudQPH8wT2XExB02sn/9oU7IgQKxS4qfca1kC1kX6zD5zpbQ7Xn8" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+ozL0rADDDz2rC4fFVjlBpq5nl+YBjZA1Mz" crossorigin="anonymous"></script>
</body>
</html>

todos/templates/todos/delete_task.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Tarea</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <h2>Eliminar Tarea</h2>
        <p>¿Estás seguro de que deseas eliminar la siguiente tarea?</p>
        <ul class="list-group">
            <li class="list-group-item">
                <strong>Título:</strong> {{ task.title }}
            </li>
            <li class="list-group-item">
                <strong>Descripción:</strong> {{ task.description }}
            </li>
            <li class="list-group-item">
                <strong>¿Resuelta?:</strong> {% if task.is_resolved %}Sí{% else %}No{% endif %}
            </li>
        </ul>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger mt-3">Confirmar Eliminación</button>
            <a href="{% url 'home' %}" class="btn btn-secondary mt-3">Cancelar</a>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js" integrity="sha384-NRQ2vP5QN7WuKiY1AqpOT9GhHvRlxD5WuAuAETOHSKAU4A8lW5a0ccVi3XvrzZJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+ozL0rADDDz2rC4fFVjlBpq5nl+YBjZA1Mz" crossorigin="anonymous"></script>
</body>
</html>

todos/templates/todos/home.html
{% extends 'base.html' %}

{% block title %}
    Página de Inicio
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">¡Bienvenido a tu aplicación de gestión de tareas!</h1>
        <hr class="my-4">
        <a class="btn btn-primary btn-lg" href="{% url 'create_task' %}" role="button">Crear Nueva Tarea</a>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h2>Tareas No Resueltas Recientes</h2>
            <ul class="list-group">
                {% if unresolved_tasks %}
                    {% for task in unresolved_tasks %}
                        <li class="list-group-item">{{ task.title }}</li>
                    {% endfor %}
                {% else %}
                    <li class="list-group-item">No hay tareas no resueltas disponibles.</li>
                {% endif %}
            </ul>
        </div>
        <div class="col-md-6">
            <h2>Tareas Resueltas Recientes</h2>
            <ul class="list-group">
                {% if resolved_tasks %}
                    {% for task in resolved_tasks %}
                        <li class="list-group-item">{{ task.title }}</li>
                    {% endfor %}
                {% else %}
                    <li class="list-group-item">No hay tareas resueltas disponibles.</li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

todos/templates/todos/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Iniciar Sesión</title>
</head>
<body>
    <h2>Iniciar Sesión</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar Sesión</button>
    </form>
</body>
</html>

todos/templates/todos/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Registro de Usuario</title>
</head>
<body>
    <h2>Registro de Usuario</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrarse</button>
    </form>
</body>
</html>

todos/templates/todos/todo_list_ids.html
{% extends 'base.html' %}

{% block title %}Lista de IDs - Tareas App{% endblock %}

{% block content %}
    <h2>Lista de IDs</h2>
    <ul class="list-group">
        {% for todo in todos %}
        <li class="list-group-item">
            ID: {{ todo.id }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}

todos/templates/todos/todo_list_ids_titles.html
{% extends 'base.html' %}

{% block title %}Lista de IDs y Títulos - Tareas App{% endblock %}

{% block content %}
    <h2>Lista de IDs y Títulos</h2>
    <ul class="list-group">
        {% for todo in todos %}
        <li class="list-group-item">
            ID: {{ todo.id }} - Título: {{ todo.title }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}

todos/templates/todos/todo_list_ids_userids.html
{% extends 'base.html' %}

{% block title %}IDs y User IDs - Tareas App{% endblock %}

{% block content %}
    <h2>IDs y User IDs</h2>
    <ul class="list-group">
        {% for todo in todos %}
        <li class="list-group-item">
            ID: {{ todo.id }} - User ID: {{ todo.user_id }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}

todos/templates/todos/todo_list_resolved.html
{% extends 'base.html' %}

{% block title %}Tareas Resueltas - Tareas App{% endblock %}

{% block content %}
    <h2>Tareas Resueltas</h2>
    <ul class="list-group">
        {% for todo in todos %}
        <li class="list-group-item">
            {{ todo.title }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}

todos/templates/todos/todo_list_resolved_userids.html
{% extends 'base.html' %}

{% block title %}Tareas Resueltas con User IDs - Tareas App{% endblock %}

{% block content %}
    <h2>Tareas Resueltas con User IDs</h2>
    <ul class="list-group">
        {% for todo in todos %}
        <li class="list-group-item">
            {{ todo.title }} - User ID: {{ todo.user_id }}
        </li>
        {% endfor %}
    </ul>
{% endblock %}

todos/templates/todos/todo_list_unresolved.html
{% extends 'base.html' %}

{% block title %}Tareas No Resueltas - Tareas App{% endblock %}

{% block content %}
    <h2>Tareas No Resueltas</h2>
    <ul class="list-group">
        {% for todo in todos %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ todo.title }}
            <div>
                <a href="{% url 'update_task' todo.id %}" class="btn btn-primary btn-sm">Editar</a>
                <a href="{% url 'delete_task' todo.id %}" class="btn btn-danger btn-sm">Eliminar</a>
            </div>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

todos/templates/todos/todo_list_unresolved_userids.html
{% extends 'base.html' %}

{% block title %}Tareas No Resueltas con User IDs - Tareas App{% endblock %}

{% block content %}
    <h2>Tareas No Resueltas con User IDs</h2>
    <ul class="list-group">
        {% for todo in todos %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ todo.title }} - User ID: {{ todo.user_id }}
            <div>
                <a href="{% url 'update_task' todo.id %}" class="btn btn-primary btn-sm">Editar</a>
                <a href="{% url 'delete_task' todo.id %}" class="btn btn-danger btn-sm">Eliminar</a>
            </div>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

todos/templates/todos/update_task.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar Tarea</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <h2>Actualizar Tarea</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Título:</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ task.title }}">
            </div>
            <div class="form-group">
                <label for="description">Descripción:</label>
                <textarea id="description" name="description" class="form-control">{{ task.description }}</textarea>
            </div>
            <div class="form-group">
                <label for="user">Usuario:</label>
                <select id="user" name="user" class="form-control">
                    {% for user in users %}
                        <option value="{{ user.id }}" {% if task.user.id == user.id %}selected{% endif %}>{{ user.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-check">
                <input type="checkbox" id="is_resolved" name="is_resolved" class="form-check-input" {% if task.is_resolved %}checked{% endif %}>
                <label for="is_resolved" class="form-check-label">¿Resuelta?</label>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Actualizar Tarea</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js" integrity="sha384-NRQ2vP5QN7WuKiY1AqpOT9GhHvRlxD5WuAuAETOHSKAU4A8lW5a0ccVi3XvrzZJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+ozL0rADDDz2rC4fFVjlBpq5nl+YBjZA1Mz" crossorigin="anonymous"></script>
</body>
</html>